p8105\_hw1\_jdr2191
================
Jess Rosenberg

## Problem 1

First, I will load the tidyverse.

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

    ## ✓ ggplot2 3.3.5     ✓ purrr   0.3.4
    ## ✓ tibble  3.1.4     ✓ dplyr   1.0.7
    ## ✓ tidyr   1.1.3     ✓ stringr 1.4.0
    ## ✓ readr   2.0.1     ✓ forcats 0.5.1

    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

Next, I will create a dataframe that includes a random sample of size 10
from a standard Normal distribution, a logical vector indicating whether
elements of the sample are greater than 0, a character vector of length
10, and a factor vector of length 10, with 3 different factor “levels”.
I will also ensure that this was done correctly by looking at the
dataframe after I create the required variables.

``` r
problem1_df = tibble(
  norm_samp = rnorm(10),
  norm_samp_greater10 = norm_samp > 0,
  letter_char = c("A","B","C","D","E","F","G","H","I","J"),
  color_factor = factor(c("purple","purple","purple","purple","blue","blue","blue",
                        "red","red","red")),
)
 problem1_df
```

    ## # A tibble: 10 × 4
    ##    norm_samp norm_samp_greater10 letter_char color_factor
    ##        <dbl> <lgl>               <chr>       <fct>       
    ##  1     0.785 TRUE                A           purple      
    ##  2     0.435 TRUE                B           purple      
    ##  3    -1.15  FALSE               C           purple      
    ##  4     0.318 TRUE                D           purple      
    ##  5    -1.84  FALSE               E           blue        
    ##  6    -0.654 FALSE               F           blue        
    ##  7     0.667 TRUE                G           blue        
    ##  8    -0.247 FALSE               H           red         
    ##  9     0.381 TRUE                I           red         
    ## 10    -1.59  FALSE               J           red

Next, I will attempt to take the mean of each of these variables I just
created.

``` r
mean(pull(problem1_df, norm_samp))
```

    ## [1] -0.2895

``` r
mean(pull(problem1_df, norm_samp_greater10))
```

    ## [1] 0.5

``` r
mean(pull(problem1_df, letter_char))
```

    ## Warning in mean.default(pull(problem1_df, letter_char)): argument is not numeric
    ## or logical: returning NA

    ## [1] NA

``` r
mean(pull(problem1_df, color_factor))
```

    ## Warning in mean.default(pull(problem1_df, color_factor)): argument is not
    ## numeric or logical: returning NA

    ## [1] NA

The mean of norm\_samp (numeric variable) = -0.1230888.

The mean norm\_samp\_greater10 (logical variable) = 0.4.

The mean of letter\_char (character variable) = cannot be calculated
(the argument is not numeric or logical: returning NA).

The mean of color\_factor (factor variable) = cannot be calculated
(argument is not numeric or logical: returning NA).

To further investigate what is happening here, I will convert the
logical, character, and factor varibles to numeric variables.

``` r
as.numeric(pull(problem1_df, norm_samp_greater10))
as.numeric(pull(problem1_df, letter_char))
```

    ## Warning: NAs introduced by coercion

``` r
as.numeric(pull(problem1_df, color_factor))
```

`The logical variable is converted to all 1s and 0s. This happens because our logical variable is binary (false becomes 0 and true becomes 1). When we took the mean of the logical variable, we got a result, which makes sense as we are taking the mean of 0s and 1s, which is possible. The chracter variable results in all NAs with a warning message. This happens because character variables cannot easily be converted to numeric variables as the categories do not have numeric equivalents. When we tried to take the mean of then character vector we got an error, which makes sense because it is not possible to take the mean of character/text values. The factor variable is converted into 1s, 2s and 3s, where each level corresponds to a number. We were previously unable to take the mean of the vector variable as each level was text, but we are able to convert a factor variable to a numeric variable and subsequently take its mean.`

## Problem 2

First, I will load the penguins dataset.

``` r
data("penguins", package = "palmerpenguins")
```

In order to describe the penguins dataset, I will run some code to find
the number of observations, rows, and columns, as well as the mean value
for flipper length (with flipper lengths of NA excluded).

``` r
view(penguins)
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

``` r
mean(pull(penguins, flipper_length_mm), na.rm = T)
```

    ## [1] 200.9152

`The dataset includes penguin species, island, bill length and depth, flipper length, body mass, sex and year. There are 8 columns and 344 rows. The mean flipper length is 200.9152 mm.`

Next, I will generate a scatterplot of flipper\_length\_mm vs
bill\_length\_mm with color points using the species variable.

``` r
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color=species)) + geom_point()
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_jdr2191_files/figure-gfm/unnamed-chunk-7-1.png)<!-- -->

Lastly, I will save this scatterplot to my working directory.

``` r
ggsave("penguin_plot.pdf", height = 4, width = 6)
```

    ## Warning: Removed 2 rows containing missing values (geom_point).
